//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Limba {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Limba() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Limba", typeof(Limba).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account data.
        /// </summary>
        public static string actualizareDateContToolStripMenuItem {
            get {
                return ResourceManager.GetString("actualizareDateContToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string adaugareCategorieToolStripMenuItem {
            get {
                return ResourceManager.GetString("adaugareCategorieToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add existing product.
        /// </summary>
        public static string adaugareProdusExistentToolStripMenuItem {
            get {
                return ResourceManager.GetString("adaugareProdusExistentToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new product.
        /// </summary>
        public static string adaugareProdusNouToolStripMenuItem {
            get {
                return ResourceManager.GetString("adaugareProdusNouToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string adaugareToolStripMenuItem {
            get {
                return ResourceManager.GetString("adaugareToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdaugare {
            get {
                return ResourceManager.GetString("btnAdaugare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Category.
        /// </summary>
        public static string btnAddNewCategory {
            get {
                return ResourceManager.GetString("btnAddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string btnModificaNume {
            get {
                return ResourceManager.GetString("btnModificaNume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string btnVinde {
            get {
                return ResourceManager.GetString("btnVinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnVizualizare {
            get {
                return ResourceManager.GetString("btnVizualizare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Quantity!.
        /// </summary>
        public static string cantitateInvalida {
            get {
                return ResourceManager.GetString("cantitateInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Quantity!.
        /// </summary>
        public static string cantitateInvalidaProductExistent {
            get {
                return ResourceManager.GetString("cantitateInvalidaProductExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string cautareDetaliataToolStripMenuItem {
            get {
                return ResourceManager.GetString("cautareDetaliataToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give administrator rights to this account.
        /// </summary>
        public static string checkBoxAdminAccount {
            get {
                return ResourceManager.GetString("checkBoxAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string comboBoxCategorie {
            get {
                return ResourceManager.GetString("comboBoxCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string comboBoxSelectCategory {
            get {
                return ResourceManager.GetString("comboBoxSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string comboBoxTip {
            get {
                return ResourceManager.GetString("comboBoxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        public static string confirmaStergere {
            get {
                return ResourceManager.GetString("confirmaStergere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created!.
        /// </summary>
        public static string contCreat {
            get {
                return ResourceManager.GetString("contCreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name!.
        /// </summary>
        public static string denumireInvalida {
            get {
                return ResourceManager.GetString("denumireInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Description!.
        /// </summary>
        public static string descriereInvalida {
            get {
                return ResourceManager.GetString("descriereInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string englishToolStripMenuItem {
            get {
                return ResourceManager.GetString("englishToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Quantity!.
        /// </summary>
        public static string eroareCantInvalida {
            get {
                return ResourceManager.GetString("eroareCantInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id!.
        /// </summary>
        public static string eroareIdProdusInvalid {
            get {
                return ResourceManager.GetString("eroareIdProdusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id!.
        /// </summary>
        public static string idInvalidProductExistent {
            get {
                return ResourceManager.GetString("idInvalidProductExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your current Last Name. Enter another one!.
        /// </summary>
        public static string introducetiNumediferit {
            get {
                return ResourceManager.GetString("introducetiNumediferit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Last Name!.
        /// </summary>
        public static string introducetiNumeNou {
            get {
                return ResourceManager.GetString("introducetiNumeNou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password!.
        /// </summary>
        public static string introducetiParola {
            get {
                return ResourceManager.GetString("introducetiParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Actual Password!.
        /// </summary>
        public static string introducetiparolaActuala {
            get {
                return ResourceManager.GetString("introducetiparolaActuala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your current First Name. Enter another one!.
        /// </summary>
        public static string introducetiPrenumediferit {
            get {
                return ResourceManager.GetString("introducetiPrenumediferit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid First Name!.
        /// </summary>
        public static string introducetiPrenumeNou {
            get {
                return ResourceManager.GetString("introducetiPrenumeNou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username!.
        /// </summary>
        public static string introducetiUsername {
            get {
                return ResourceManager.GetString("introducetiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string labelCantitate {
            get {
                return ResourceManager.GetString("labelCantitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string labelCategorie {
            get {
                return ResourceManager.GetString("labelCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string labelDataExpirare {
            get {
                return ResourceManager.GetString("labelDataExpirare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Date.
        /// </summary>
        public static string labelDataIesire {
            get {
                return ResourceManager.GetString("labelDataIesire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string labelDataIntrare {
            get {
                return ResourceManager.GetString("labelDataIntrare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string labelDenumire {
            get {
                return ResourceManager.GetString("labelDenumire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string labelDescriere {
            get {
                return ResourceManager.GetString("labelDescriere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string labelNume {
            get {
                return ResourceManager.GetString("labelNume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Last Name:.
        /// </summary>
        public static string labelNumeNou {
            get {
                return ResourceManager.GetString("labelNumeNou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Password:.
        /// </summary>
        public static string labelParolaActuala {
            get {
                return ResourceManager.GetString("labelParolaActuala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string labelParolaNoua {
            get {
                return ResourceManager.GetString("labelParolaNoua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string labelPrenume {
            get {
                return ResourceManager.GetString("labelPrenume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New First Name:.
        /// </summary>
        public static string labelPrenumeNou {
            get {
                return ResourceManager.GetString("labelPrenumeNou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string labelRegister {
            get {
                return ResourceManager.GetString("labelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Id:.
        /// </summary>
        public static string labelSelectId {
            get {
                return ResourceManager.GetString("labelSelectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort:.
        /// </summary>
        public static string labelSortare {
            get {
                return ResourceManager.GetString("labelSortare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string labelUsername {
            get {
                return ResourceManager.GetString("labelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string linkLabel1 {
            get {
                return ResourceManager.GetString("linkLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Last Name.
        /// </summary>
        public static string modificareNumeToolStripMenuItem {
            get {
                return ResourceManager.GetString("modificareNumeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string modificareParolaToolStripMenuItem {
            get {
                return ResourceManager.GetString("modificareParolaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify First Name.
        /// </summary>
        public static string modificarePrenumeToolStripMenuItem {
            get {
                return ResourceManager.GetString("modificarePrenumeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Category and it&apos;s products were deleted!.
        /// </summary>
        public static string notificareStergereCategorie {
            get {
                return ResourceManager.GetString("notificareStergereCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted!.
        /// </summary>
        public static string notificareStergereCont {
            get {
                return ResourceManager.GetString("notificareStergereCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted succesfully!.
        /// </summary>
        public static string notificareStergereProdus {
            get {
                return ResourceManager.GetString("notificareStergereProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Last Name!.
        /// </summary>
        public static string numeInvalid {
            get {
                return ResourceManager.GetString("numeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name changed!.
        /// </summary>
        public static string numeModificat {
            get {
                return ResourceManager.GetString("numeModificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string optionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("optionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong actual password!.
        /// </summary>
        public static string parolaActualaIncorecta {
            get {
                return ResourceManager.GetString("parolaActualaIncorecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        public static string parolaGresita {
            get {
                return ResourceManager.GetString("parolaGresita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password!.
        /// </summary>
        public static string parolaInvalida {
            get {
                return ResourceManager.GetString("parolaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed!.
        /// </summary>
        public static string parolaModificataCuSucces {
            get {
                return ResourceManager.GetString("parolaModificataCuSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid new password!.
        /// </summary>
        public static string parolaNouaInvalida {
            get {
                return ResourceManager.GetString("parolaNouaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid First Name!.
        /// </summary>
        public static string prenumeInvalid {
            get {
                return ResourceManager.GetString("prenumeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name changed!.
        /// </summary>
        public static string prenumeModificat {
            get {
                return ResourceManager.GetString("prenumeModificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added!.
        /// </summary>
        public static string produsAdaugat {
            get {
                return ResourceManager.GetString("produsAdaugat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products added!.
        /// </summary>
        public static string produseAdaugatecuSucces {
            get {
                return ResourceManager.GetString("produseAdaugatecuSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string romanianToolStripMenuItem {
            get {
                return ResourceManager.GetString("romanianToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category!.
        /// </summary>
        public static string selectatiCategorie {
            get {
                return ResourceManager.GetString("selectatiCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string selecteaza {
            get {
                return ResourceManager.GetString("selecteaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Category? The products from this category will also be deleted!.
        /// </summary>
        public static string stergereCategorie {
            get {
                return ResourceManager.GetString("stergereCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string stergereCont {
            get {
                return ResourceManager.GetString("stergereCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current account.
        /// </summary>
        public static string stergereContToolStripMenuItem {
            get {
                return ResourceManager.GetString("stergereContToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string stergereProdusToolStripMenuItem {
            get {
                return ResourceManager.GetString("stergereProdusToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string toate {
            get {
                return ResourceManager.GetString("toate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exists!.
        /// </summary>
        public static string usernameExistent {
            get {
                return ResourceManager.GetString("usernameExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username!.
        /// </summary>
        public static string usernameInvalid {
            get {
                return ResourceManager.GetString("usernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product sold succesfully!.
        /// </summary>
        public static string vanzareSucces {
            get {
                return ResourceManager.GetString("vanzareSucces", resourceCulture);
            }
        }
    }
}
